### PR TITLE
new UI style, animation on controls, fullscreen callback and title on video --WIP--

### PR DESCRIPTION
**Pull request by Liroo**
Hey, I use this package to implement videoview inside our app but there are many gaps that PR can fill.

I reviewed the interface to make it more attractive and easier. So I added cool animations
I added a title to the video might appear at the top of the view at the same time as controls.
I tried to Implement a full-screen mode but I have not succeeded without adding too many dependencies, and our applications we will manage with Navigation. so I just add a callback and a fullscreen button.

Poster is now press able to start video.
- [x]  UI controls style
- [x]  UI Animations (mount/unmount)
- [x]  UI Animation (controls disappears after short timing)
- [x]  UI title style
- [x]  added 'flow' on project (not locally implemented)
- [x]  FullScreen mode (at this time callback is called but you should handle this in you own app... In our own app we use react-native-orientation and the experimental navigation from react-native)
- [x]  ReadMe update
- [x]  Review of Demo then add a gif to README with new Demo
- update Slider where you could hit the slider anywhere (PR must be on dependencie, not on this repo)

### CODE REVIEW

**Comment by Liroo** [comment]
FullScreen is implemented with Navigator (only view is implemented, not actually seekTo, correct animations, etc...)

EDIT: just see I have to set fullscreen icon controlled

**Comment by Liroo** [comment]
Check this PR @ldn0x7dc

**Comment by Liroo** [comment]
Didn't add a gif to README, I don't have enough time :/ My last commit is about how to handle fullscreen in JS with Navigator, there's some bugs but I have to work on another project, please comment this PR if you want to discuss 🍖  😸

**Comment by kingctan** [comment]
how to pause? trouble with this. please help,thanks.
and when switch to fullscreen, 2 videos, and 2 audios, 
and navigator back to exit, this will always be playing background.

**Comment by Liroo** [comment]
That was a tentative to play video in full screen but there is definitively not possible without changing the native module... Or getting a native view which can expand (or js view at root).
I close this PR w/o answer of the owner of the repo....

**Pull request closed without merging**
